name: Deploy static content to FTP Server

on:
  workflow_dispatch:
  schedule:
    - cron: "0 * * * *"
  push:
    branches: ["main"]
    paths-ignore:
      - 'README.md'
      - 'index.html'

permissions:
  contents: read

concurrency:
  group: "ftp-deploy"
  cancel-in-progress: false

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Deploy to FTP Server
        uses: SamKirkland/FTP-Deploy-Action@4.2.0
        with:
          ftp-server: ${{ secrets.FTP_SERVEUR }}
          ftp-username: ${{ secrets.FTP_USERNAME }}
          ftp-password: ${{ secrets.FTP_PASSWORD }}
          local-dir: "./website"
          remote-dir: "./v2/"
